server:
  port: 9017

spring:
  h2:
    console:
      enabled: true

  datasource:
    platform: h2
    url: jdbc:h2:mem:db-produit

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false